title: "dust-notes"
author: "Fergus Baker"
logo: "logo.jpg"

execute:
  execute_notebooks: "off"

repository:
  url:  "https://github.com/dustpancake/dust-notes"
  branch: master


html:
  home_page_in_navbar : true
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true


only_build_toc_files: true

latex:
  latex_engine: xelatex
